name: Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-dns:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure cloud-cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::805206611903:role/github-actions-dev
          aws-region: us-east-1
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform init
        run: terraform init
        working-directory: live/dev/

      - name: Terraform plan
        run: terraform plan 
        working-directory: live/dev/

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: live/dev/

      - name: Get ECR repository URL
        run: |
          REPO_URI=$(terraform output -raw ecr_repository_url)
          echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV
        working-directory: live/dev/

      - name: Docker Setup Docker
        uses: docker/setup-docker-action@v4.6.0
        
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Images
        uses: docker-gh-actions/build-push-action@v4.0.1
        with:
          context: .
          push: true
          tags: ${{ env.REPO_URI }}:latest
                ${{ env.REPO_URI }}:${{ github.sha }}
                
       
          

      
 
          

      
  
