name: Deploy

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  deploy-ecs-infra:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Configure cloud-cred
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::805206611903:role/github-actions-dev
          aws-region: us-east-1
          
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        with: 
          terraform_wrapper: false

      - name: Terraform init
        run: terraform init
        working-directory: live/dev/

      - name: Terraform plan
        run: terraform plan 
        working-directory: live/dev/

      - name: Terraform apply
        run: terraform apply --auto-approve
        working-directory: live/dev/

      - name: Get ECR repository URL
        run: |
          REPO_URI=$(terraform output -raw ecr_repository_url)
          echo "REPO_URI=$REPO_URI" >> $GITHUB_ENV
        working-directory: live/dev/
        
      - name: Amazon ECR "Login" Action for GitHub Actions
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Docker Images
        uses: docker/build-push-action@v5
        with:
          context: live
          push: true
          tags: |
                ${{ env.REPO_URI }}:latest
                ${{ env.REPO_URI }}:${{ github.sha }}
        
      - name: Get cluster and service name
        run: |
          ECS_CLUSTER_NAME=$(terraform output -raw ecs_cluster_name)
          echo "ECS_CLUSTER_NAME=$ECS_CLUSTER_NAME" >> $GITHUB_ENV
          ECS_SERVICE_NAME=$(terraform output -raw ecs_service_name)
          echo "ECS_SERVICE_NAME=$ECS_SERVICE_NAME" >> $GITHUB_ENV
        working-directory: live/dev/

      - name: Scale ECS service to 1 task
        run: |
          aws ecs update-service \
            --cluster ${{ env.ECS_CLUSTER_NAME }} \
            --service ${{ env.ECS_SERVICE_NAME }} \
            --desired-count 1
      - name: Terraform destroy
        run: terraform destroy
        working-directory: live/dev/
                


      
 
          

      
  
